
[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "web3",
    "python-dotenv",
    "cdp>=0.0.2",
    "eth-account>=0.13.4",
]
